/**
 * "Attention Is All You Need" (Vaswani et al., 2017, arXiv:1706.03762v7) as the
 * block list the example lays out. Generated by scripts/paper.py from the arXiv
 * HTML: text only, figures and tables dropped, math flattened to spans.
 */

export type Face = 'b' | 'c' | 'i' | 'm' | 'r' | 'sub' | 'sup';

export type Kind =
  | 'title'
  | 'author'
  | 'note'
  | 'abstract-title'
  | 'abstract'
  | 'h1'
  | 'p'
  | 'h2'
  | 'h3'
  | 'eq'
  | 'li'
  | 'ref';

/** One styled run of text. Faces select a font within the block's size. */
export type Span = [face: Face, text: string];

export interface Block {
  kind: Kind;
  spans: Span[];
}

export const PAPER: Block[] = [
  { kind: 'title', spans: [['r', 'Attention Is All You Need']] },
  {
    kind: 'author',
    spans: [
      ['b', 'Ashish Vaswani'],
      ['r', '  ·  Google Brain  ·  '],
      ['c', 'avaswani@google.com'],
    ],
  },
  {
    kind: 'author',
    spans: [
      ['b', 'Noam Shazeer'],
      ['r', '  ·  Google Brain  ·  '],
      ['c', 'noam@google.com'],
    ],
  },
  {
    kind: 'author',
    spans: [
      ['b', 'Niki Parmar'],
      ['r', '  ·  Google Research  ·  '],
      ['c', 'nikip@google.com'],
    ],
  },
  {
    kind: 'author',
    spans: [
      ['b', 'Jakob Uszkoreit'],
      ['r', '  ·  Google Research  ·  '],
      ['c', 'usz@google.com'],
    ],
  },
  {
    kind: 'author',
    spans: [
      ['b', 'Llion Jones'],
      ['r', '  ·  Google Research  ·  '],
      ['c', 'llion@google.com'],
    ],
  },
  {
    kind: 'author',
    spans: [
      ['b', 'Aidan N. Gomez'],
      ['r', '  ·  University of Toronto  ·  '],
      ['c', 'aidan@cs.toronto.edu'],
    ],
  },
  {
    kind: 'author',
    spans: [
      ['b', 'Łukasz Kaiser'],
      ['r', '  ·  Google Brain  ·  '],
      ['c', 'lukaszkaiser@google.com'],
    ],
  },
  {
    kind: 'author',
    spans: [
      ['b', 'Illia Polosukhin'],
      ['r', '  ·  '],
      ['c', 'illia.polosukhin@gmail.com'],
    ],
  },
  {
    kind: 'note',
    spans: [
      [
        'r',
        'Equal contribution. Listing order is random. Jakob proposed replacing RNNs with self-attention and started the effort to evaluate this idea. Ashish, with Illia, designed and implemented the first Transformer models and has been crucially involved in every aspect of this work. Noam proposed scaled dot-product attention, multi-head attention and the parameter-free position representation and became the other person involved in nearly every detail. Niki designed, implemented, tuned and evaluated countless model variants in our original codebase and tensor2tensor. Llion also experimented with novel model variants, was responsible for our initial codebase, and efficient inference and visualizations. Lukasz and Aidan spent countless long days designing various parts of and implementing tensor2tensor, replacing our earlier codebase, greatly improving results and massively accelerating our research.',
      ],
    ],
  },
  { kind: 'note', spans: [['r', 'Work performed while at Google Brain.']] },
  { kind: 'note', spans: [['r', 'Work performed while at Google Research.']] },
  { kind: 'abstract-title', spans: [['r', 'Abstract']] },
  {
    kind: 'abstract',
    spans: [
      [
        'r',
        'The dominant sequence transduction models are based on complex recurrent or convolutional neural networks that include an encoder and a decoder. The best performing models also connect the encoder and decoder through an attention mechanism. We propose a new simple network architecture, the Transformer, based solely on attention mechanisms, dispensing with recurrence and convolutions entirely. Experiments on two machine translation tasks show these models to be superior in quality while being more parallelizable and requiring significantly less time to train. Our model achieves 28.4 BLEU on the WMT 2014 English-to-German translation task, improving over the existing best results, including ensembles, by over 2 BLEU. On the WMT 2014 English-to-French translation task, our model establishes a new single-model state-of-the-art BLEU score of 41.8 after training for 3.5 days on eight GPUs, a small fraction of the training costs of the best models from the literature. We show that the Transformer generalizes well to other tasks by applying it successfully to English constituency parsing both with large and limited training data.',
      ],
    ],
  },
  { kind: 'h1', spans: [['r', '1 Introduction']] },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'Recurrent neural networks, long short-term memory [13] and gated recurrent [7] neural networks in particular, have been firmly established as state of the art approaches in sequence modeling and transduction problems such as language modeling and machine translation [35, 2, 5]. Numerous efforts have since continued to push the boundaries of recurrent language models and encoder-decoder architectures [38, 24, 15].',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'Recurrent models typically factor computation along the symbol positions of the input and output sequences. Aligning the positions to steps in computation time, they generate a sequence of hidden states ',
      ],
      ['m', 'hₜ'],
      ['r', ', as a function of the previous hidden state '],
      ['m', 'h'],
      ['sub', 't−1'],
      ['r', ' and the input for position '],
      ['m', 't'],
      [
        'r',
        '. This inherently sequential nature precludes parallelization within training examples, which becomes critical at longer sequence lengths, as memory constraints limit batching across examples. Recent work has achieved significant improvements in computational efficiency through factorization tricks [21] and conditional computation [32], while also improving model performance in case of the latter. The fundamental constraint of sequential computation, however, remains.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'Attention mechanisms have become an integral part of compelling sequence modeling and transduction models in various tasks, allowing modeling of dependencies without regard to their distance in the input or output sequences [2, 19]. In all but a few cases [27], however, such attention mechanisms are used in conjunction with a recurrent network.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'In this work we propose the Transformer, a model architecture eschewing recurrence and instead relying entirely on an attention mechanism to draw global dependencies between input and output. The Transformer allows for significantly more parallelization and can reach a new state of the art in translation quality after being trained for as little as twelve hours on eight P100 GPUs.',
      ],
    ],
  },
  { kind: 'h1', spans: [['r', '2 Background']] },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'The goal of reducing sequential computation also forms the foundation of the Extended Neural GPU [16], ByteNet [18] and ConvS2S [9], all of which use convolutional neural networks as basic building block, computing hidden representations in parallel for all input and output positions. In these models, the number of operations required to relate signals from two arbitrary input or output positions grows in the distance between positions, linearly for ConvS2S and logarithmically for ByteNet. This makes it more difficult to learn dependencies between distant positions [12]. In the Transformer this is reduced to a constant number of operations, albeit at the cost of reduced effective resolution due to averaging attention-weighted positions, an effect we counteract with Multi-Head Attention as described in section 3.2.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'Self-attention, sometimes called intra-attention is an attention mechanism relating different positions of a single sequence in order to compute a representation of the sequence. Self-attention has been used successfully in a variety of tasks including reading comprehension, abstractive summarization, textual entailment and learning task-independent sentence representations [4, 27, 28, 22].',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'End-to-end memory networks are based on a recurrent attention mechanism instead of sequence-aligned recurrence and have been shown to perform well on simple-language question answering and language modeling tasks [34].',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'To the best of our knowledge, however, the Transformer is the first transduction model relying entirely on self-attention to compute representations of its input and output without using sequence-aligned RNNs or convolution. In the following sections, we will describe the Transformer, motivate self-attention and discuss its advantages over models such as [17, 18] and [9].',
      ],
    ],
  },
  { kind: 'h1', spans: [['r', '3 Model Architecture']] },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'Most competitive neural sequence transduction models have an encoder-decoder structure [5, 2, 35]. Here, the encoder maps an input sequence of symbol representations (',
      ],
      ['m', 'x'],
      ['r', '₁, '],
      ['m', '…'],
      ['r', ', '],
      ['m', 'xₙ'],
      ['r', ') to a sequence of continuous representations '],
      ['m', '𝐳'],
      ['r', ' = ('],
      ['m', 'z'],
      ['r', '₁, '],
      ['m', '…'],
      ['r', ', '],
      ['m', 'zₙ'],
      ['r', '). Given '],
      ['m', '𝐳'],
      ['r', ', the decoder then generates an output sequence ('],
      ['m', 'y'],
      ['r', '₁, '],
      ['m', '…'],
      ['r', ', '],
      ['m', 'yₘ'],
      [
        'r',
        ') of symbols one element at a time. At each step the model is auto-regressive [10], consuming the previously generated symbols as additional input when generating the next.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'The Transformer follows this overall architecture using stacked self-attention and point-wise, fully connected layers for both the encoder and decoder, shown in the left and right halves of Figure 1, respectively.',
      ],
    ],
  },
  { kind: 'h2', spans: [['r', '3.1 Encoder and Decoder Stacks']] },
  {
    kind: 'p',
    spans: [
      ['b', 'Encoder: '],
      ['r', 'The encoder is composed of a stack of '],
      ['m', 'N'],
      [
        'r',
        ' = 6 identical layers. Each layer has two sub-layers. The first is a multi-head self-attention mechanism, and the second is a simple, position-wise fully connected feed-forward network. We employ a residual connection [11] around each of the two sub-layers, followed by layer normalization [1]. That is, the output of each sub-layer is LayerNorm(',
      ],
      ['m', 'x'],
      ['r', ' + Sublayer('],
      ['m', 'x'],
      ['r', ')), where Sublayer('],
      ['m', 'x'],
      [
        'r',
        ') is the function implemented by the sub-layer itself. To facilitate these residual connections, all sub-layers in the model, as well as the embedding layers, produce outputs of dimension ',
      ],
      ['m', 'd'],
      ['sub', 'model'],
      ['r', ' = 512.'],
    ],
  },
  {
    kind: 'p',
    spans: [
      ['b', 'Decoder: '],
      ['r', 'The decoder is also composed of a stack of '],
      ['m', 'N'],
      [
        'r',
        ' = 6 identical layers. In addition to the two sub-layers in each encoder layer, the decoder inserts a third sub-layer, which performs multi-head attention over the output of the encoder stack. Similar to the encoder, we employ residual connections around each of the sub-layers, followed by layer normalization. We also modify the self-attention sub-layer in the decoder stack to prevent positions from attending to subsequent positions. This masking, combined with fact that the output embeddings are offset by one position, ensures that the predictions for position ',
      ],
      ['m', 'i'],
      ['r', ' can depend only on the known outputs at positions less than '],
      ['m', 'i'],
      ['r', '.'],
    ],
  },
  { kind: 'h2', spans: [['r', '3.2 Attention']] },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'An attention function can be described as mapping a query and a set of key-value pairs to an output, where the query, keys, values, and output are all vectors. The output is computed as a weighted sum of the values, where the weight assigned to each value is computed by a compatibility function of the query with the corresponding key.',
      ],
    ],
  },
  { kind: 'h3', spans: [['r', '3.2.1 Scaled Dot-Product Attention']] },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'We call our particular attention "Scaled Dot-Product Attention" (Figure 2). The input consists of queries and keys of dimension ',
      ],
      ['m', 'dₖ'],
      ['r', ', and values of dimension '],
      ['m', 'dᵥ'],
      ['r', '. We compute the dot products of the query with all keys, divide each by √'],
      ['m', 'dₖ'],
      ['r', ', and apply a softmax function to obtain the weights on the values.'],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'In practice, we compute the attention function on a set of queries simultaneously, packed together into a matrix ',
      ],
      ['m', 'Q'],
      ['r', '. The keys and values are also packed together into matrices '],
      ['m', 'K'],
      ['r', ' and '],
      ['m', 'V'],
      ['r', '. We compute the matrix of outputs as:'],
    ],
  },
  {
    kind: 'eq',
    spans: [
      ['r', 'Attention('],
      ['m', 'Q'],
      ['r', ', '],
      ['m', 'K'],
      ['r', ', '],
      ['m', 'V'],
      ['r', ') = softmax(('],
      ['m', 'QKᵀ'],
      ['r', ')/(√'],
      ['m', 'dₖ'],
      ['r', '))'],
      ['m', 'V'],
      ['r', '   (1)'],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'The two most commonly used attention functions are additive attention [2], and dot-product (multiplicative) attention. Dot-product attention is identical to our algorithm, except for the scaling factor of 1/(√',
      ],
      ['m', 'dₖ'],
      [
        'r',
        '). Additive attention computes the compatibility function using a feed-forward network with a single hidden layer. While the two are similar in theoretical complexity, dot-product attention is much faster and more space-efficient in practice, since it can be implemented using highly optimized matrix multiplication code.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      ['r', 'While for small values of '],
      ['m', 'dₖ'],
      [
        'r',
        ' the two mechanisms perform similarly, additive attention outperforms dot product attention without scaling for larger values of ',
      ],
      ['m', 'dₖ'],
      ['r', ' [3]. We suspect that for large values of '],
      ['m', 'dₖ'],
      [
        'r',
        ', the dot products grow large in magnitude, pushing the softmax function into regions where it has extremely small gradients . To counteract this effect, we scale the dot products by 1/(√',
      ],
      ['m', 'dₖ'],
      ['r', ').'],
    ],
  },
  {
    kind: 'note',
    spans: [
      ['r', 'To illustrate why the dot products get large, assume that the components of '],
      ['m', 'q'],
      ['r', ' and '],
      ['m', 'k'],
      [
        'r',
        ' are independent random variables with mean 0 and variance 1. Then their dot product, ',
      ],
      ['m', 'q'],
      ['r', '⋅'],
      ['m', 'k'],
      ['r', ' = ∑ᵢ₌₁'],
      ['sup', 'd_k'],
      ['m', 'qᵢkᵢ'],
      ['r', ', has mean 0 and variance '],
      ['m', 'dₖ'],
      ['r', '.'],
    ],
  },
  { kind: 'h3', spans: [['r', '3.2.2 Multi-Head Attention']] },
  {
    kind: 'p',
    spans: [
      ['r', 'Instead of performing a single attention function with '],
      ['m', 'd'],
      ['sub', 'model'],
      [
        'r',
        '-dimensional keys, values and queries, we found it beneficial to linearly project the queries, keys and values ',
      ],
      ['m', 'h'],
      ['r', ' times with different, learned linear projections to '],
      ['m', 'dₖ'],
      ['r', ', '],
      ['m', 'dₖ'],
      ['r', ' and '],
      ['m', 'dᵥ'],
      [
        'r',
        ' dimensions, respectively. On each of these projected versions of queries, keys and values we then perform the attention function in parallel, yielding ',
      ],
      ['m', 'dᵥ'],
      [
        'r',
        '-dimensional output values. These are concatenated and once again projected, resulting in the final values, as depicted in Figure 2.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'Multi-head attention allows the model to jointly attend to information from different representation subspaces at different positions. With a single attention head, averaging inhibits this.',
      ],
    ],
  },
  {
    kind: 'eq',
    spans: [
      ['r', 'MultiHead('],
      ['m', 'Q'],
      ['r', ', '],
      ['m', 'K'],
      ['r', ', '],
      ['m', 'V'],
      ['r', ') = Concat(head₁, '],
      ['m', '…'],
      ['r', ', head'],
      ['m', 'ₕ'],
      ['r', ')'],
      ['m', 'W'],
      ['sup', 'O'],
    ],
  },
  {
    kind: 'eq',
    spans: [
      ['r', 'where head'],
      ['m', 'ᵢ'],
      ['r', ' = Attention('],
      ['m', 'QWᵢ'],
      ['sup', 'Q'],
      ['r', ', '],
      ['m', 'KWᵢ'],
      ['sup', 'K'],
      ['r', ', '],
      ['m', 'VWᵢ'],
      ['sup', 'V'],
      ['r', ')'],
    ],
  },
  {
    kind: 'p',
    spans: [
      ['r', 'Where the projections are parameter matrices '],
      ['m', 'Wᵢ'],
      ['sup', 'Q'],
      ['r', ' ∈ '],
      ['m', 'ℝ'],
      ['sup', 'd_model×d_k'],
      ['r', ', '],
      ['m', 'Wᵢ'],
      ['sup', 'K'],
      ['r', ' ∈ '],
      ['m', 'ℝ'],
      ['sup', 'd_model×d_k'],
      ['r', ', '],
      ['m', 'Wᵢ'],
      ['sup', 'V'],
      ['r', ' ∈ '],
      ['m', 'ℝ'],
      ['sup', 'd_model×d_v'],
      ['r', ' and '],
      ['m', 'W'],
      ['sup', 'O'],
      ['r', ' ∈ '],
      ['m', 'ℝ'],
      ['sup', 'hd_v×d_model'],
      ['r', '.'],
    ],
  },
  {
    kind: 'p',
    spans: [
      ['r', 'In this work we employ '],
      ['m', 'h'],
      ['r', ' = 8 parallel attention layers, or heads. For each of these we use '],
      ['m', 'dₖ'],
      ['r', ' = '],
      ['m', 'dᵥ'],
      ['r', ' = '],
      ['m', 'd'],
      ['sub', 'model'],
      ['r', '/'],
      ['m', 'h'],
      [
        'r',
        ' = 64. Due to the reduced dimension of each head, the total computational cost is similar to that of single-head attention with full dimensionality.',
      ],
    ],
  },
  { kind: 'h3', spans: [['r', '3.2.3 Applications of Attention in our Model']] },
  {
    kind: 'p',
    spans: [['r', 'The Transformer uses multi-head attention in three different ways:']],
  },
  {
    kind: 'li',
    spans: [
      [
        'r',
        '• In "encoder-decoder attention" layers, the queries come from the previous decoder layer, and the memory keys and values come from the output of the encoder. This allows every position in the decoder to attend over all positions in the input sequence. This mimics the typical encoder-decoder attention mechanisms in sequence-to-sequence models such as [38, 2, 9].',
      ],
    ],
  },
  {
    kind: 'li',
    spans: [
      [
        'r',
        '• The encoder contains self-attention layers. In a self-attention layer all of the keys, values and queries come from the same place, in this case, the output of the previous layer in the encoder. Each position in the encoder can attend to all positions in the previous layer of the encoder.',
      ],
    ],
  },
  {
    kind: 'li',
    spans: [
      [
        'r',
        '• Similarly, self-attention layers in the decoder allow each position in the decoder to attend to all positions in the decoder up to and including that position. We need to prevent leftward information flow in the decoder to preserve the auto-regressive property. We implement this inside of scaled dot-product attention by masking out (setting to  − ',
      ],
      ['m', '∞'],
      [
        'r',
        ') all values in the input of the softmax which correspond to illegal connections. See Figure 2.',
      ],
    ],
  },
  { kind: 'h2', spans: [['r', '3.3 Position-wise Feed-Forward Networks']] },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'In addition to attention sub-layers, each of the layers in our encoder and decoder contains a fully connected feed-forward network, which is applied to each position separately and identically. This consists of two linear transformations with a ReLU activation in between.',
      ],
    ],
  },
  {
    kind: 'eq',
    spans: [
      ['r', 'FFN('],
      ['m', 'x'],
      ['r', ') = max(0, '],
      ['m', 'xW'],
      ['r', '₁ + '],
      ['m', 'b'],
      ['r', '₁)'],
      ['m', 'W'],
      ['r', '₂ + '],
      ['m', 'b'],
      ['r', '₂   (2)'],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'While the linear transformations are the same across different positions, they use different parameters from layer to layer. Another way of describing this is as two convolutions with kernel size 1. The dimensionality of input and output is ',
      ],
      ['m', 'd'],
      ['sub', 'model'],
      ['r', ' = 512, and the inner-layer has dimensionality '],
      ['m', 'd'],
      ['sub', 'ff'],
      ['r', ' = 2048.'],
    ],
  },
  { kind: 'h2', spans: [['r', '3.4 Embeddings and Softmax']] },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'Similarly to other sequence transduction models, we use learned embeddings to convert the input tokens and output tokens to vectors of dimension ',
      ],
      ['m', 'd'],
      ['sub', 'model'],
      [
        'r',
        '. We also use the usual learned linear transformation and softmax function to convert the decoder output to predicted next-token probabilities. In our model, we share the same weight matrix between the two embedding layers and the pre-softmax linear transformation, similar to [30]. In the embedding layers, we multiply those weights by √(',
      ],
      ['m', 'd'],
      ['sub', 'model'],
      ['r', ').'],
    ],
  },
  { kind: 'h2', spans: [['r', '3.5 Positional Encoding']] },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'Since our model contains no recurrence and no convolution, in order for the model to make use of the order of the sequence, we must inject some information about the relative or absolute position of the tokens in the sequence. To this end, we add "positional encodings" to the input embeddings at the bottoms of the encoder and decoder stacks. The positional encodings have the same dimension ',
      ],
      ['m', 'd'],
      ['sub', 'model'],
      [
        'r',
        ' as the embeddings, so that the two can be summed. There are many choices of positional encodings, learned and fixed [9].',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [['r', 'In this work, we use sine and cosine functions of different frequencies:']],
  },
  {
    kind: 'eq',
    spans: [
      ['m', 'PE'],
      ['sub', '(pos,2i)'],
      ['r', ' = '],
      ['m', 'sin'],
      ['r', '('],
      ['m', 'pos'],
      ['r', '/10000'],
      ['sup', '2i/d_model'],
      ['r', ')'],
    ],
  },
  {
    kind: 'eq',
    spans: [
      ['m', 'PE'],
      ['sub', '(pos,2i+1)'],
      ['r', ' = '],
      ['m', 'cos'],
      ['r', '('],
      ['m', 'pos'],
      ['r', '/10000'],
      ['sup', '2i/d_model'],
      ['r', ')'],
    ],
  },
  {
    kind: 'p',
    spans: [
      ['r', 'where '],
      ['m', 'pos'],
      ['r', ' is the position and '],
      ['m', 'i'],
      [
        'r',
        ' is the dimension. That is, each dimension of the positional encoding corresponds to a sinusoid. The wavelengths form a geometric progression from 2',
      ],
      ['m', 'π'],
      ['r', ' to 10000⋅2'],
      ['m', 'π'],
      [
        'r',
        '. We chose this function because we hypothesized it would allow the model to easily learn to attend by relative positions, since for any fixed offset ',
      ],
      ['m', 'k'],
      ['r', ', '],
      ['m', 'PE'],
      ['r', 'ₚₒₛ₊ₖ can be represented as a linear function of '],
      ['m', 'PE'],
      ['r', 'ₚₒₛ.'],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'We also experimented with using learned positional embeddings [9] instead, and found that the two versions produced nearly identical results (see Table 3 row (E)). We chose the sinusoidal version because it may allow the model to extrapolate to sequence lengths longer than the ones encountered during training.',
      ],
    ],
  },
  { kind: 'h1', spans: [['r', '4 Why Self-Attention']] },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'In this section we compare various aspects of self-attention layers to the recurrent and convolutional layers commonly used for mapping one variable-length sequence of symbol representations (',
      ],
      ['m', 'x'],
      ['r', '₁, '],
      ['m', '…'],
      ['r', ', '],
      ['m', 'xₙ'],
      ['r', ') to another sequence of equal length ('],
      ['m', 'z'],
      ['r', '₁, '],
      ['m', '…'],
      ['r', ', '],
      ['m', 'zₙ'],
      ['r', '), with '],
      ['m', 'xᵢ'],
      ['r', ', '],
      ['m', 'zᵢ'],
      ['r', ' ∈ '],
      ['m', 'ℝ'],
      ['sup', 'd'],
      [
        'r',
        ', such as a hidden layer in a typical sequence transduction encoder or decoder. Motivating our use of self-attention we consider three desiderata.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'One is the total computational complexity per layer. Another is the amount of computation that can be parallelized, as measured by the minimum number of sequential operations required.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'The third is the path length between long-range dependencies in the network. Learning long-range dependencies is a key challenge in many sequence transduction tasks. One key factor affecting the ability to learn such dependencies is the length of the paths forward and backward signals have to traverse in the network. The shorter these paths between any combination of positions in the input and output sequences, the easier it is to learn long-range dependencies [12]. Hence we also compare the maximum path length between any two input and output positions in networks composed of the different layer types.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'As noted in Table 1, a self-attention layer connects all positions with a constant number of sequentially executed operations, whereas a recurrent layer requires ',
      ],
      ['m', 'O'],
      ['r', '('],
      ['m', 'n'],
      [
        'r',
        ') sequential operations. In terms of computational complexity, self-attention layers are faster than recurrent layers when the sequence length ',
      ],
      ['m', 'n'],
      ['r', ' is smaller than the representation dimensionality '],
      ['m', 'd'],
      [
        'r',
        ', which is most often the case with sentence representations used by state-of-the-art models in machine translations, such as word-piece [38] and byte-pair [31] representations. To improve computational performance for tasks involving very long sequences, self-attention could be restricted to considering only a neighborhood of size ',
      ],
      ['m', 'r'],
      [
        'r',
        ' in the input sequence centered around the respective output position. This would increase the maximum path length to ',
      ],
      ['m', 'O'],
      ['r', '('],
      ['m', 'n'],
      ['r', '/'],
      ['m', 'r'],
      ['r', '). We plan to investigate this approach further in future work.'],
    ],
  },
  {
    kind: 'p',
    spans: [
      ['r', 'A single convolutional layer with kernel width '],
      ['m', 'k'],
      ['r', '<'],
      ['m', 'n'],
      [
        'r',
        ' does not connect all pairs of input and output positions. Doing so requires a stack of ',
      ],
      ['m', 'O'],
      ['r', '('],
      ['m', 'n'],
      ['r', '/'],
      ['m', 'k'],
      ['r', ') convolutional layers in the case of contiguous kernels, or '],
      ['m', 'O'],
      ['r', '('],
      ['m', 'logₖ'],
      ['r', '('],
      ['m', 'n'],
      [
        'r',
        ')) in the case of dilated convolutions [18], increasing the length of the longest paths between any two positions in the network. Convolutional layers are generally more expensive than recurrent layers, by a factor of ',
      ],
      ['m', 'k'],
      ['r', '. Separable convolutions [6], however, decrease the complexity considerably, to '],
      ['m', 'O'],
      ['r', '('],
      ['m', 'k'],
      ['r', '⋅'],
      ['m', 'n'],
      ['r', '⋅'],
      ['m', 'd'],
      ['r', ' + '],
      ['m', 'n'],
      ['r', '⋅'],
      ['m', 'd'],
      ['r', '²). Even with '],
      ['m', 'k'],
      ['r', ' = '],
      ['m', 'n'],
      [
        'r',
        ', however, the complexity of a separable convolution is equal to the combination of a self-attention layer and a point-wise feed-forward layer, the approach we take in our model.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'As side benefit, self-attention could yield more interpretable models. We inspect attention distributions from our models and present and discuss examples in the appendix. Not only do individual attention heads clearly learn to perform different tasks, many appear to exhibit behavior related to the syntactic and semantic structure of the sentences.',
      ],
    ],
  },
  { kind: 'h1', spans: [['r', '5 Training']] },
  { kind: 'p', spans: [['r', 'This section describes the training regime for our models.']] },
  { kind: 'h2', spans: [['r', '5.1 Training Data and Batching']] },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'We trained on the standard WMT 2014 English-German dataset consisting of about 4.5 million sentence pairs. Sentences were encoded using byte-pair encoding [3], which has a shared source-target vocabulary of about 37000 tokens. For English-French, we used the significantly larger WMT 2014 English-French dataset consisting of 36M sentences and split tokens into a 32000 word-piece vocabulary [38]. Sentence pairs were batched together by approximate sequence length. Each training batch contained a set of sentence pairs containing approximately 25000 source tokens and 25000 target tokens.',
      ],
    ],
  },
  { kind: 'h2', spans: [['r', '5.2 Hardware and Schedule']] },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'We trained our models on one machine with 8 NVIDIA P100 GPUs. For our base models using the hyperparameters described throughout the paper, each training step took about 0.4 seconds. We trained the base models for a total of 100,000 steps or 12 hours. For our big models,(described on the bottom line of table 3), step time was 1.0 seconds. The big models were trained for 300,000 steps (3.5 days).',
      ],
    ],
  },
  { kind: 'h2', spans: [['r', '5.3 Optimizer']] },
  {
    kind: 'p',
    spans: [
      ['r', 'We used the Adam optimizer [20] with '],
      ['m', 'β'],
      ['r', '₁ = 0.9, '],
      ['m', 'β'],
      ['r', '₂ = 0.98 and '],
      ['m', 'ϵ'],
      ['r', ' = 10'],
      ['sup', '−9'],
      ['r', '. We varied the learning rate over the course of training, according to the formula:'],
    ],
  },
  {
    kind: 'eq',
    spans: [
      ['m', 'lrate'],
      ['r', ' = '],
      ['m', 'd'],
      ['sub', 'model'],
      ['sup', '−0.5'],
      ['r', '⋅min('],
      ['m', 'step_num'],
      ['sup', '−0.5'],
      ['r', ', '],
      ['m', 'step_num'],
      ['r', '⋅'],
      ['m', 'warmup_steps'],
      ['sup', '−1.5'],
      ['r', ')   (3)'],
    ],
  },
  {
    kind: 'p',
    spans: [
      ['r', 'This corresponds to increasing the learning rate linearly for the first '],
      ['m', 'warmup_steps'],
      [
        'r',
        ' training steps, and decreasing it thereafter proportionally to the inverse square root of the step number. We used ',
      ],
      ['m', 'warmup_steps'],
      ['r', ' = 4000.'],
    ],
  },
  { kind: 'h2', spans: [['r', '5.4 Regularization']] },
  { kind: 'p', spans: [['r', 'We employ three types of regularization during training:']] },
  {
    kind: 'p',
    spans: [
      ['b', 'Residual Dropout '],
      [
        'r',
        'We apply dropout [33] to the output of each sub-layer, before it is added to the sub-layer input and normalized. In addition, we apply dropout to the sums of the embeddings and the positional encodings in both the encoder and decoder stacks. For the base model, we use a rate of ',
      ],
      ['m', 'P'],
      ['sub', 'drop'],
      ['r', ' = 0.1.'],
    ],
  },
  {
    kind: 'p',
    spans: [
      ['b', 'Label Smoothing '],
      ['r', 'During training, we employed label smoothing of value '],
      ['m', 'ϵ'],
      [
        'r',
        'ₗₛ = 0.1 [36]. This hurts perplexity, as the model learns to be more unsure, but improves accuracy and BLEU score.',
      ],
    ],
  },
  { kind: 'h1', spans: [['r', '6 Results']] },
  { kind: 'h2', spans: [['r', '6.1 Machine Translation']] },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'On the WMT 2014 English-to-German translation task, the big transformer model (Transformer (big) in Table 2) outperforms the best previously reported models (including ensembles) by more than 2.0 BLEU, establishing a new state-of-the-art BLEU score of 28.4. The configuration of this model is listed in the bottom line of Table 3. Training took 3.5 days on 8 P100 GPUs. Even our base model surpasses all previously published models and ensembles, at a fraction of the training cost of any of the competitive models.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'On the WMT 2014 English-to-French translation task, our big model achieves a BLEU score of 41.0, outperforming all of the previously published single models, at less than 1/4 the training cost of the previous state-of-the-art model. The Transformer (big) model trained for English-to-French used dropout rate ',
      ],
      ['m', 'P'],
      ['sub', 'drop'],
      ['r', ' = 0.1, instead of 0.3.'],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'For the base models, we used a single model obtained by averaging the last 5 checkpoints, which were written at 10-minute intervals. For the big models, we averaged the last 20 checkpoints. We used beam search with a beam size of 4 and length penalty ',
      ],
      ['m', 'α'],
      [
        'r',
        ' = 0.6 [38]. These hyperparameters were chosen after experimentation on the development set. We set the maximum output length during inference to input length + 50, but terminate early when possible [38].',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'Table 2 summarizes our results and compares our translation quality and training costs to other model architectures from the literature. We estimate the number of floating point operations used to train a model by multiplying the training time, the number of GPUs used, and an estimate of the sustained single-precision floating-point capacity of each GPU .',
      ],
    ],
  },
  {
    kind: 'note',
    spans: [
      [
        'r',
        'We used values of 2.8, 3.7, 6.0 and 9.5 TFLOPS for K80, K40, M40 and P100, respectively.',
      ],
    ],
  },
  { kind: 'h2', spans: [['r', '6.2 Model Variations']] },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'To evaluate the importance of different components of the Transformer, we varied our base model in different ways, measuring the change in performance on English-to-German translation on the development set, newstest2013. We used beam search as described in the previous section, but no checkpoint averaging. We present these results in Table 3.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'In Table 3 rows (A), we vary the number of attention heads and the attention key and value dimensions, keeping the amount of computation constant, as described in Section 3.2.2. While single-head attention is 0.9 BLEU worse than the best setting, quality also drops off with too many heads.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      ['r', 'In Table 3 rows (B), we observe that reducing the attention key size '],
      ['m', 'dₖ'],
      [
        'r',
        ' hurts model quality. This suggests that determining compatibility is not easy and that a more sophisticated compatibility function than dot product may be beneficial. We further observe in rows (C) and (D) that, as expected, bigger models are better, and dropout is very helpful in avoiding over-fitting. In row (E) we replace our sinusoidal positional encoding with learned positional embeddings [9], and observe nearly identical results to the base model.',
      ],
    ],
  },
  { kind: 'h2', spans: [['r', '6.3 English Constituency Parsing']] },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'To evaluate if the Transformer can generalize to other tasks we performed experiments on English constituency parsing. This task presents specific challenges: the output is subject to strong structural constraints and is significantly longer than the input. Furthermore, RNN sequence-to-sequence models have not been able to attain state-of-the-art results in small-data regimes [37].',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      ['r', 'We trained a 4-layer transformer with '],
      ['m', 'd'],
      ['sub', 'model'],
      [
        'r',
        ' = 1024 on the Wall Street Journal (WSJ) portion of the Penn Treebank [25], about 40K training sentences. We also trained it in a semi-supervised setting, using the larger high-confidence and BerkleyParser corpora from with approximately 17M sentences [37]. We used a vocabulary of 16K tokens for the WSJ only setting and a vocabulary of 32K tokens for the semi-supervised setting.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'We performed only a small number of experiments to select the dropout, both attention and residual (section 5.4), learning rates and beam size on the Section 22 development set, all other parameters remained unchanged from the English-to-German base translation model. During inference, we increased the maximum output length to input length + 300. We used a beam size of 21 and ',
      ],
      ['m', 'α'],
      ['r', ' = 0.3 for both WSJ only and the semi-supervised setting.'],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'Our results in Table 4 show that despite the lack of task-specific tuning our model performs surprisingly well, yielding better results than all previously reported models with the exception of the Recurrent Neural Network Grammar [8].',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'In contrast to RNN sequence-to-sequence models [37], the Transformer outperforms the BerkeleyParser [29] even when training only on the WSJ training set of 40K sentences.',
      ],
    ],
  },
  { kind: 'h1', spans: [['r', '7 Conclusion']] },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'In this work, we presented the Transformer, the first sequence transduction model based entirely on attention, replacing the recurrent layers most commonly used in encoder-decoder architectures with multi-headed self-attention.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'For translation tasks, the Transformer can be trained significantly faster than architectures based on recurrent or convolutional layers. On both WMT 2014 English-to-German and WMT 2014 English-to-French translation tasks, we achieve a new state of the art. In the former task our best model outperforms even all previously reported ensembles.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      [
        'r',
        'We are excited about the future of attention-based models and plan to apply them to other tasks. We plan to extend the Transformer to problems involving input and output modalities other than text and to investigate local, restricted attention mechanisms to efficiently handle large inputs and outputs such as images, audio and video. Making generation less sequential is another research goals of ours.',
      ],
    ],
  },
  {
    kind: 'p',
    spans: [
      ['r', 'The code we used to train and evaluate our models is available at '],
      ['c', 'https://github.com/tensorflow/tensor2tensor'],
      ['r', '.'],
    ],
  },
  {
    kind: 'p',
    spans: [
      ['b', 'Acknowledgements '],
      [
        'r',
        'We are grateful to Nal Kalchbrenner and Stephan Gouws for their fruitful comments, corrections and inspiration.',
      ],
    ],
  },
  { kind: 'h1', spans: [['r', 'Attention Visualizations']] },
  { kind: 'h1', spans: [['r', 'References']] },
  {
    kind: 'ref',
    spans: [
      ['r', '[1] Jimmy Lei Ba, Jamie Ryan Kiros, and Geoffrey E Hinton. Layer normalization. '],
      ['i', 'arXiv preprint arXiv:1607.06450'],
      ['r', ', 2016.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[2] Dzmitry Bahdanau, Kyunghyun Cho, and Yoshua Bengio. Neural machine translation by jointly learning to align and translate. ',
      ],
      ['i', 'CoRR'],
      ['r', ', abs/1409.0473, 2014.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[3] Denny Britz, Anna Goldie, Minh-Thang Luong, and Quoc V. Le. Massive exploration of neural machine translation architectures. ',
      ],
      ['i', 'CoRR'],
      ['r', ', abs/1703.03906, 2017.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[4] Jianpeng Cheng, Li Dong, and Mirella Lapata. Long short-term memory-networks for machine reading. ',
      ],
      ['i', 'arXiv preprint arXiv:1601.06733'],
      ['r', ', 2016.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[5] Kyunghyun Cho, Bart van Merrienboer, Caglar Gulcehre, Fethi Bougares, Holger Schwenk, and Yoshua Bengio. Learning phrase representations using rnn encoder-decoder for statistical machine translation. ',
      ],
      ['i', 'CoRR'],
      ['r', ', abs/1406.1078, 2014.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[6] Francois Chollet. Xception: Deep learning with depthwise separable convolutions. ',
      ],
      ['i', 'arXiv preprint arXiv:1610.02357'],
      ['r', ', 2016.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[7] Junyoung Chung, Çaglar Gülçehre, Kyunghyun Cho, and Yoshua Bengio. Empirical evaluation of gated recurrent neural networks on sequence modeling. ',
      ],
      ['i', 'CoRR'],
      ['r', ', abs/1412.3555, 2014.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[8] Chris Dyer, Adhiguna Kuncoro, Miguel Ballesteros, and Noah A. Smith. Recurrent neural network grammars. In ',
      ],
      ['i', 'Proc. of NAACL'],
      ['r', ', 2016.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[9] Jonas Gehring, Michael Auli, David Grangier, Denis Yarats, and Yann N. Dauphin. Convolutional sequence to sequence learning. ',
      ],
      ['i', 'arXiv preprint arXiv:1705.03122v2'],
      ['r', ', 2017.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      ['r', '[10] Alex Graves. Generating sequences with recurrent neural networks. '],
      ['i', 'arXiv preprint arXiv:1308.0850'],
      ['r', ', 2013.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[11] Kaiming He, Xiangyu Zhang, Shaoqing Ren, and Jian Sun. Deep residual learning for image recognition. In ',
      ],
      ['i', 'Proceedings of the IEEE Conference on Computer Vision and Pattern Recognition'],
      ['r', ', pages 770–778, 2016.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[12] Sepp Hochreiter, Yoshua Bengio, Paolo Frasconi, and Jürgen Schmidhuber. Gradient flow in recurrent nets: the difficulty of learning long-term dependencies, 2001.',
      ],
    ],
  },
  {
    kind: 'ref',
    spans: [
      ['r', '[13] Sepp Hochreiter and Jürgen Schmidhuber. Long short-term memory. '],
      ['i', 'Neural computation'],
      ['r', ', 9(8):1735–1780, 1997.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[14] Zhongqiang Huang and Mary Harper. Self-training PCFG grammars with latent annotations across languages. In ',
      ],
      [
        'i',
        'Proceedings of the 2009 Conference on Empirical Methods in Natural Language Processing',
      ],
      ['r', ', pages 832–841. ACL, August 2009.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[15] Rafal Jozefowicz, Oriol Vinyals, Mike Schuster, Noam Shazeer, and Yonghui Wu. Exploring the limits of language modeling. ',
      ],
      ['i', 'arXiv preprint arXiv:1602.02410'],
      ['r', ', 2016.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      ['r', '[16] Łukasz Kaiser and Samy Bengio. Can active memory replace attention? In '],
      ['i', 'Advances in Neural Information Processing Systems, (NIPS)'],
      ['r', ', 2016.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      ['r', '[17] Łukasz Kaiser and Ilya Sutskever. Neural GPUs learn algorithms. In '],
      ['i', 'International Conference on Learning Representations (ICLR)'],
      ['r', ', 2016.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[18] Nal Kalchbrenner, Lasse Espeholt, Karen Simonyan, Aaron van den Oord, Alex Graves, and Koray Kavukcuoglu. Neural machine translation in linear time. ',
      ],
      ['i', 'arXiv preprint arXiv:1610.10099v2'],
      ['r', ', 2017.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[19] Yoon Kim, Carl Denton, Luong Hoang, and Alexander M. Rush. Structured attention networks. In ',
      ],
      ['i', 'International Conference on Learning Representations'],
      ['r', ', 2017.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      ['r', '[20] Diederik Kingma and Jimmy Ba. Adam: A method for stochastic optimization. In '],
      ['i', 'ICLR'],
      ['r', ', 2015.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      ['r', '[21] Oleksii Kuchaiev and Boris Ginsburg. Factorization tricks for LSTM networks. '],
      ['i', 'arXiv preprint arXiv:1703.10722'],
      ['r', ', 2017.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[22] Zhouhan Lin, Minwei Feng, Cicero Nogueira dos Santos, Mo Yu, Bing Xiang, Bowen Zhou, and Yoshua Bengio. A structured self-attentive sentence embedding. ',
      ],
      ['i', 'arXiv preprint arXiv:1703.03130'],
      ['r', ', 2017.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[23] Minh-Thang Luong, Quoc V. Le, Ilya Sutskever, Oriol Vinyals, and Lukasz Kaiser. Multi-task sequence to sequence learning. ',
      ],
      ['i', 'arXiv preprint arXiv:1511.06114'],
      ['r', ', 2015.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[24] Minh-Thang Luong, Hieu Pham, and Christopher D Manning. Effective approaches to attention-based neural machine translation. ',
      ],
      ['i', 'arXiv preprint arXiv:1508.04025'],
      ['r', ', 2015.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[25] Mitchell P Marcus, Mary Ann Marcinkiewicz, and Beatrice Santorini. Building a large annotated corpus of english: The penn treebank. ',
      ],
      ['i', 'Computational linguistics'],
      ['r', ', 19(2):313–330, 1993.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[26] David McClosky, Eugene Charniak, and Mark Johnson. Effective self-training for parsing. In ',
      ],
      [
        'i',
        'Proceedings of the Human Language Technology Conference of the NAACL, Main Conference',
      ],
      ['r', ', pages 152–159. ACL, June 2006.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[27] Ankur Parikh, Oscar Täckström, Dipanjan Das, and Jakob Uszkoreit. A decomposable attention model. In ',
      ],
      ['i', 'Empirical Methods in Natural Language Processing'],
      ['r', ', 2016.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[28] Romain Paulus, Caiming Xiong, and Richard Socher. A deep reinforced model for abstractive summarization. ',
      ],
      ['i', 'arXiv preprint arXiv:1705.04304'],
      ['r', ', 2017.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[29] Slav Petrov, Leon Barrett, Romain Thibaux, and Dan Klein. Learning accurate, compact, and interpretable tree annotation. In ',
      ],
      [
        'i',
        'Proceedings of the 21st International Conference on Computational Linguistics and 44th Annual Meeting of the ACL',
      ],
      ['r', ', pages 433–440. ACL, July 2006.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[30] Ofir Press and Lior Wolf. Using the output embedding to improve language models. ',
      ],
      ['i', 'arXiv preprint arXiv:1608.05859'],
      ['r', ', 2016.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[31] Rico Sennrich, Barry Haddow, and Alexandra Birch. Neural machine translation of rare words with subword units. ',
      ],
      ['i', 'arXiv preprint arXiv:1508.07909'],
      ['r', ', 2015.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[32] Noam Shazeer, Azalia Mirhoseini, Krzysztof Maziarz, Andy Davis, Quoc Le, Geoffrey Hinton, and Jeff Dean. Outrageously large neural networks: The sparsely-gated mixture-of-experts layer. ',
      ],
      ['i', 'arXiv preprint arXiv:1701.06538'],
      ['r', ', 2017.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[33] Nitish Srivastava, Geoffrey E Hinton, Alex Krizhevsky, Ilya Sutskever, and Ruslan Salakhutdinov. Dropout: a simple way to prevent neural networks from overfitting. ',
      ],
      ['i', 'Journal of Machine Learning Research'],
      ['r', ', 15(1):1929–1958, 2014.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[34] Sainbayar Sukhbaatar, Arthur Szlam, Jason Weston, and Rob Fergus. End-to-end memory networks. In C. Cortes, N. D. Lawrence, D. D. Lee, M. Sugiyama, and R. Garnett, editors, ',
      ],
      ['i', 'Advances in Neural Information Processing Systems 28'],
      ['r', ', pages 2440–2448. Curran Associates, Inc., 2015.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[35] Ilya Sutskever, Oriol Vinyals, and Quoc VV Le. Sequence to sequence learning with neural networks. In ',
      ],
      ['i', 'Advances in Neural Information Processing Systems'],
      ['r', ', pages 3104–3112, 2014.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[36] Christian Szegedy, Vincent Vanhoucke, Sergey Ioffe, Jonathon Shlens, and Zbigniew Wojna. Rethinking the inception architecture for computer vision. ',
      ],
      ['i', 'CoRR'],
      ['r', ', abs/1512.00567, 2015.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[37] Vinyals & Kaiser, Koo, Petrov, Sutskever, and Hinton. Grammar as a foreign language. In ',
      ],
      ['i', 'Advances in Neural Information Processing Systems'],
      ['r', ', 2015.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[38] Yonghui Wu, Mike Schuster, Zhifeng Chen, Quoc V Le, Mohammad Norouzi, Wolfgang Macherey, Maxim Krikun, Yuan Cao, Qin Gao, Klaus Macherey, et al. Google’s neural machine translation system: Bridging the gap between human and machine translation. ',
      ],
      ['i', 'arXiv preprint arXiv:1609.08144'],
      ['r', ', 2016.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[39] Jie Zhou, Ying Cao, Xuguang Wang, Peng Li, and Wei Xu. Deep recurrent models with fast-forward connections for neural machine translation. ',
      ],
      ['i', 'CoRR'],
      ['r', ', abs/1606.04199, 2016.'],
    ],
  },
  {
    kind: 'ref',
    spans: [
      [
        'r',
        '[40] Muhua Zhu, Yue Zhang, Wenliang Chen, Min Zhang, and Jingbo Zhu. Fast and accurate shift-reduce constituent parsing. In ',
      ],
      ['i', 'Proceedings of the 51st Annual Meeting of the ACL (Volume 1: Long Papers)'],
      ['r', ', pages 434–443. ACL, August 2013.'],
    ],
  },
];
